{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "#memory",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<iframe src=\"https://trapavilion-grafana-discord-exporter.trap.show/photos\" width=\"1400\" height=\"280\" frameborder=\"0\">"
   }
  },
  {
   "title": "Discord メッセージ数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(discord_messages_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Discord リアクション数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(discord_reactions_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Discord 写真数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(discord_photos_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Discord リアクション数ランキング",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(discord_reactions_total) by (user))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Discordアナウンス", "type": "news", "gridPos": { "h": 16, "w": 12, "x": 0, "y": 17 } },
  {
   "title": "Discord 写真投稿数ランキング",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(discord_photos_total) by (user))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}