{
 "title": "traPavilion-Editing",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "traPavilion 残り時間", "type": "grafana-clock-panel", "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "ホール",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "time_table_event_end_seconds{location=\"ホール\"} and on(name) time_table_room_current_event_info{location=\"ホール\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROOM0",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "time_table_event_end_seconds{location=\"ROOM0\"} and on(name) time_table_room_current_event_info{location=\"ROOM0\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ホール",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "time_table_room_next_start_seconds{location=\"ホール\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time_table_room_next_event_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROOM0",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "time_table_room_next_start_seconds{location=\"ROOM0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time_table_room_next_event_info{location=\"ROOM0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#memory",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "options": {
    "content": "<iframe src=\"https://trapavilion-grafana-discord-exporter.trap.show/photos\" width=\"1400\" height=\"280\" frameborder=\"0\">"
   }
  },
  { "title": "イベント", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 12 } },
  {
   "title": "ホール タイムテーブル",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "time_table_event_start_seconds{location=\"ホール\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROOM0 タイムテーブル",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "time_table_event_start_seconds{location=\"ROOM0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Discord", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 20 } },
  { "title": "運営アナウンス", "type": "news", "gridPos": { "h": 13, "w": 5, "x": 0, "y": 21 } },
  {
   "title": "メッセージ数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(discord_messages_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "リアクション数ランキング",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(discord_reactions_total) by (user))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "リアクション数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(discord_reactions_total)", "legendFormat": "__auto" }
   ]
  },
  { "title": "traQ", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 25 } },
  {
   "title": "オンラインユーザー数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traq_online_users{job=\"traq\",user_type=\"user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "合計ユーザー数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traq_users_count{user_type=\"user-active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "合計ボット数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traq_users_count{user_type=\"bot-active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "メッセージ数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "traq_messages_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "写真投稿数ランキング",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(discord_photos_total) by (user))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "写真数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(discord_photos_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "オンラインボット数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traq_online_users{user_type=\"bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "パブリックチャンネル数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traq_channels_count_total{job=\"traq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "合計メッセージ数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "traq_messages_count_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "CTFコンテスト", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 34 } },
  { "title": "会場ネットワーク", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 34 } },
  {
   "title": "景品獲得者数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "columns": [
      { "selector": "date", "text": "Date", "type": "timestamp" },
      { "selector": "value", "text": "Value", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://script.google.com/macros/s/AKfycbyBWEr3qCmO57jcBfYA9sevmaz5RI4dl-VcGGVKBpU_hitUlV912od6u-1yaySF2bSaMA/exec",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "sheet", "value": "getters" }
      ]
     }
    }
   ]
  },
  {
   "title": "景品残数",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "https://script.google.com/macros/s/AKfycbyBWEr3qCmO57jcBfYA9sevmaz5RI4dl-VcGGVKBpU_hitUlV912od6u-1yaySF2bSaMA/exec",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "sheet", "value": "remaining" }
      ]
     }
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bandwidth_bits_per_second",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bandwidth_bits_per_second",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_latency_seconds{stat=\"iqm\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_latency_seconds{stat=\"iqm\"}",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}