{
 "title": "Event",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": " ホール 次のイベント",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "time_table_room_next_event_info{location=\"ホール\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time_table_room_seconds_until_next{location=\"ホール\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROOM0 次のイベント",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "time_table_room_next_event_info{location=\"ROOM0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time_table_room_seconds_until_next{location=\"ROOM0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ホール タイムテーブル",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "time_table_event_start_seconds{location=\"ホール\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROOM0 タイムテーブル",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "time_table_event_start_seconds{location=\"ROOM0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}