{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Discord",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "メッセージ数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(discord_messages_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "リアクション数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(discord_reactions_total)", "legendFormat": "__auto" }
   ]
  },
  { "title": "traQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "オンラインユーザー数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traq_online_users{job=\"traq\",user_type=\"user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "パブリックチャンネル数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traq_channels_count_total{job=\"traq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "合計メッセージ数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "traq_messages_count_total", "legendFormat": "__auto" }
   ]
  }
 ]
}